#!/bin/bash
COUNTER=1
while(true) do
 ./start
curl "https://api.telegram.org/bot408816668:AAFij7E4PouQijy58RkgVSuRHzecxkqStYI/sendmessage" -F "chat_id=-1001124558242" -F "text=JarChi NOW RUNNING"
let COUNTER=COUNTER+1 
done
