#!/usr/bin/env bash

cd $HOME/JarChi
function print_logo() {
	echo -e "\033[38;5;600m"
	echo -e "          JarChi"
	echo -e "\n\e[36m"
}

if [ ! -f ./tg ]; then
    echo "tg not found"
    echo "Run $0 install"
    exit 1
 fi

 
  print_logo
   echo -e "\033[38;5;208m"
   echo -e "                        JarChi                           "
   echo -e "\033[0;00m"
   echo -e "\e[36m"
curl "https://api.telegram.org/bot408816668:AAFij7E4PouQijy58RkgVSuRHzecxkqStYI/sendmessage" -F "chat_id=-" -F "text= JarChi IS NOW RUNNING "
   ./tg -s ./bot/tabchi.lua
